kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx-namespace

spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: nginx-job-pod
      labels:
        app: nginx-job
    spec:
      containers:
       - name: batch-container
         image: busybox:latest
         command: ["echo", "-c", "Hello from the Kubernetes Job! && sleep 10"]   
      restartPolicy: Never